-- 코드를 입력하세요
SELECT DISTINCT MILK_CARTS.CART_ID
FROM (
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) MILK_CARTS, (
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) YOGURT_CARTS
WHERE MILK_CARTS.CART_ID = YOGURT_CARTS.CART_ID;