-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, B.TOTAL_PRICE TOTAL_SALES
FROM 
(SELECT WRITER_ID, SUM(PRICE) TOTAL_PRICE
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_PRICE >= 700000) B
LEFT JOIN USED_GOODS_USER U
ON U.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES
# SELECT * FROM USED_GOODS_BOARD WHERE STATUS = 'DONE' ORDER BY WRITER_ID, PRICE