-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON RH.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND RH.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CAR_ID DESC;